services:
  # Symfony PHP service
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: symfony_app
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - symfony_network
    depends_on:
      - db
    environment:
      - SYMFONY_ENV=dev

  # MySQL service
  db:
    image: mysql:8.0
    container_name: symfony_db
    ports:
      - "3306:3306"  # Expose MySQL port
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    networks:
      - symfony_network

  # Nginx service
  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    networks:
      - symfony_network
    depends_on:
      - app

networks:
  symfony_network:
    driver: bridge

volumes:
  db_data: